name: Kubernetes CI with Load Testing

on:
  pull_request:
    branches: [ main, master ]

jobs:
  k8s-load-test:
    name: K8s Deployment & Load Testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Setup KinD cluster
        uses: helm/kind-action@v1.8.0
        with:
          config: .github/k8s/kind-config.yaml
          wait: 120s
      
      - name: Install k6 for load testing
        run: |
          # Install k6 from official GPG key and repository
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6 jq
          # Verify k6 is installed
          k6 version
      
      - name: Deploy Kubernetes resources
        id: deploy
        run: |
          bash ./.github/scripts/deploy.sh
        continue-on-error: false
      
      - name: Verify deployments
        id: verify
        run: |
          bash ./.github/scripts/verify.sh
        continue-on-error: false
      
      - name: Run load test
        id: loadtest
        run: |
          echo "Running load tests..."
          bash ./.github/scripts/load-test.sh | tee load-test-results.txt

      - name: Comment PR with load test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            
            // Retry function with exponential backoff
            async function retryWithBackoff(fn, maxRetries = 5, initialDelay = 1000) {
              let retries = 0;
              while (retries < maxRetries) {
                try {
                  return await fn();
                } catch (error) {
                  retries++;
                  if (retries >= maxRetries) throw error;
                  
                  console.log(`Attempt ${retries} failed: ${error.message}`);
                  const delay = initialDelay * Math.pow(2, retries - 1);
                  console.log(`Retrying in ${delay}ms...`);
                  await new Promise(resolve => setTimeout(resolve, delay));
                }
              }
            }
            
            // Use the retry mechanism
            try {
              const results = fs.readFileSync('load-test-results.txt', 'utf8');
              let comment = `## 🚀 Load Test Results\n\n\`\`\`\n${results}\n\`\`\``;
              
              if (fs.existsSync('metrics.txt')) {
                const metrics = fs.readFileSync('metrics.txt', 'utf8');
                comment += `\n\n## 📊 Resource Utilization\n\n\`\`\`\n${metrics}\n\`\`\``;
              }
              
              const pull_number = context.payload.pull_request.number;
              
              await retryWithBackoff(async () => {
                console.log(`Posting comment to PR #${pull_number} (attempt)`);
                return github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pull_number,
                  body: comment
                });
              });
              
              console.log(`Successfully posted comment to PR #${pull_number}`);
            } catch (error) {
              console.error('Error:', error.message);
              console.error('Status:', error.status);
              console.error('Response:', error.response?.data);
              core.setFailed(`Failed to post comment: ${error.message}`);
            }
            
