name: Kubernetes CI with Load Testing

on:
  pull_request:
    branches: [ main, master ]

jobs:
  k8s-load-test:
    name: K8s Deployment & Load Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Setup KinD cluster
        uses: helm/kind-action@v1.8.0
        with:
          config: .github/k8s/kind-config.yaml
          wait: 120s
      
      - name: Install k6 for load testing
        run: |
          # Install k6 from official GPG key and repository
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6 jq
          # Verify k6 is installed
          k6 version
      
      - name: Deploy Kubernetes resources
        id: deploy
        run: |
          bash ./.github/scripts/deploy.sh
        continue-on-error: false
      
      - name: Verify deployments
        id: verify
        run: |
          bash ./.github/scripts/verify.sh
        continue-on-error: false
      
      - name: Run load test
        id: loadtest
        run: |
          echo "Running load tests..."
          bash ./.github/scripts/load-test.sh | tee load-test-results.txt
      
      - name: Comment PR with load test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            try {
              const results = fs.readFileSync('load-test-results.txt', 'utf8');
              const formattedResults = `## 🚀 Load Test Results\n\n\`\`\`\n${results}\n\`\`\``;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: formattedResults
              });
              console.log("Successfully posted load test results to PR");
            } catch (error) {
              console.error("Error posting results:", error);
              core.setFailed("Failed to post load test results");
            }
